/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';
import type {
	EnrollRequestDTO,
	EnrollRequestStatusDTO,
	UnsubscribeOptionsDTO,
	UnsubscribeParams
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === 'queryKey') continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key]
		});
	}
	return result;
};

export type unsubscribeResponse200 = {
	data: EnrollRequestDTO[];
	status: 200;
};

export type unsubscribeResponse404 = {
	data: EnrollRequestDTO[];
	status: 404;
};

export type unsubscribeResponseSuccess = unsubscribeResponse200 & {
	headers: Headers;
};
export type unsubscribeResponseError = unsubscribeResponse404 & {
	headers: Headers;
};

export type unsubscribeResponse = unsubscribeResponseSuccess | unsubscribeResponseError;

export const getUnsubscribeUrl = (id: number, params: UnsubscribeParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/enroll/${id}/unsubscribe?${stringifiedParams}`
		: `/enroll/${id}/unsubscribe`;
};

/**
 * Marks an enrollment request as unsubscribed.
 * @summary Unsubscribe from a request
 */
export const unsubscribe = async (
	id: number,
	unsubscribeOptionsDTO: UnsubscribeOptionsDTO,
	params: UnsubscribeParams,
	options?: Parameters<typeof customFetch>[1]
): Promise<unsubscribeResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<unsubscribeResponse>(getUnsubscribeUrl(id, params), {
		...options,
		method: 'PUT',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(unsubscribeOptionsDTO)
	});
};

export const getUnsubscribeMutationOptions = <
	TError = EnrollRequestDTO[],
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof unsubscribe>>,
		TError,
		UnsubscribeMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof unsubscribe>>,
	TError,
	UnsubscribeMutationVariables,
	TContext
> => {
	const mutationKey = ['unsubscribe'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof unsubscribe>>,
		UnsubscribeMutationVariables
	> = (props) => {
		const { id, data, params } = props ?? {};

		return unsubscribe(id, data, params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UnsubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof unsubscribe>>>;
export type UnsubscribeMutationBody = UnsubscribeOptionsDTO;
export type UnsubscribeMutationError = EnrollRequestDTO[];
export type UnsubscribeMutationVariables = {
	id: number;
	data: UnsubscribeOptionsDTO;
	params: UnsubscribeParams;
};

/**
 * @summary Unsubscribe from a request
 */
export const useUnsubscribe = <TError = EnrollRequestDTO[], TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof unsubscribe>>,
			TError,
			UnsubscribeMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof unsubscribe>>,
	TError,
	UnsubscribeMutationVariables,
	TContext
> => {
	return useMutation(getUnsubscribeMutationOptions(options), queryClient);
};
export type editRequestStatusResponse200 = {
	data: EnrollRequestDTO;
	status: 200;
};

export type editRequestStatusResponse404 = {
	data: EnrollRequestDTO;
	status: 404;
};

export type editRequestStatusResponseSuccess = editRequestStatusResponse200 & {
	headers: Headers;
};
export type editRequestStatusResponseError = editRequestStatusResponse404 & {
	headers: Headers;
};

export type editRequestStatusResponse =
	editRequestStatusResponseSuccess | editRequestStatusResponseError;

export const getEditRequestStatusUrl = (id: number) => {
	return `/enroll/${id}/status`;
};

/**
 * Updates the status of an enrollment request.
 * @summary Edit request status
 */
export const editRequestStatus = async (
	id: number,
	enrollRequestStatusDTO: EnrollRequestStatusDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<editRequestStatusResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<editRequestStatusResponse>(getEditRequestStatusUrl(id), {
		...options,
		method: 'PUT',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(enrollRequestStatusDTO)
	});
};

export const getEditRequestStatusMutationOptions = <
	TError = EnrollRequestDTO,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editRequestStatus>>,
		TError,
		EditRequestStatusMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editRequestStatus>>,
	TError,
	EditRequestStatusMutationVariables,
	TContext
> => {
	const mutationKey = ['editRequestStatus'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editRequestStatus>>,
		EditRequestStatusMutationVariables
	> = (props) => {
		const { id, data } = props ?? {};

		return editRequestStatus(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditRequestStatusMutationResult = NonNullable<
	Awaited<ReturnType<typeof editRequestStatus>>
>;
export type EditRequestStatusMutationBody = EnrollRequestStatusDTO;
export type EditRequestStatusMutationError = EnrollRequestDTO;
export type EditRequestStatusMutationVariables = { id: number; data: EnrollRequestStatusDTO };

/**
 * @summary Edit request status
 */
export const useEditRequestStatus = <TError = EnrollRequestDTO, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editRequestStatus>>,
			TError,
			EditRequestStatusMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof editRequestStatus>>,
	TError,
	EditRequestStatusMutationVariables,
	TContext
> => {
	return useMutation(getEditRequestStatusMutationOptions(options), queryClient);
};
export type getAllRequestsResponse200 = {
	data: EnrollRequestDTO[];
	status: 200;
};

export type getAllRequestsResponse401 = {
	data: EnrollRequestDTO[];
	status: 401;
};

export type getAllRequestsResponseSuccess = getAllRequestsResponse200 & {
	headers: Headers;
};
export type getAllRequestsResponseError = getAllRequestsResponse401 & {
	headers: Headers;
};

export type getAllRequestsResponse = getAllRequestsResponseSuccess | getAllRequestsResponseError;

export const getGetAllRequestsUrl = () => {
	return `/enroll`;
};

/**
 * Retrieves a list of all enrollment requests for the user.
 * @summary Get all enrollment requests
 */
export const getAllRequests = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllRequestsResponse> => {
	return customFetch<getAllRequestsResponse>(getGetAllRequestsUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllRequestsQueryKey = () => {
	return [`/enroll`] as const;
};

export const getGetAllRequestsQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllRequests>>,
	TError = EnrollRequestDTO[]
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRequests>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllRequestsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRequests>>> = ({ signal }) =>
		getAllRequests({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllRequests>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRequests>>>;
export type GetAllRequestsQueryError = EnrollRequestDTO[];

export function useGetAllRequests<
	TData = Awaited<ReturnType<typeof getAllRequests>>,
	TError = EnrollRequestDTO[]
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRequests>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllRequests>>,
					TError,
					Awaited<ReturnType<typeof getAllRequests>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllRequests<
	TData = Awaited<ReturnType<typeof getAllRequests>>,
	TError = EnrollRequestDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRequests>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllRequests>>,
					TError,
					Awaited<ReturnType<typeof getAllRequests>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllRequests<
	TData = Awaited<ReturnType<typeof getAllRequests>>,
	TError = EnrollRequestDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRequests>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all enrollment requests
 */

export function useGetAllRequests<
	TData = Awaited<ReturnType<typeof getAllRequests>>,
	TError = EnrollRequestDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRequests>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllRequestsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type createRequestResponse201 = {
	data: EnrollRequestDTO;
	status: 201;
};

export type createRequestResponse400 = {
	data: EnrollRequestDTO;
	status: 400;
};

export type createRequestResponseSuccess = createRequestResponse201 & {
	headers: Headers;
};
export type createRequestResponseError = createRequestResponse400 & {
	headers: Headers;
};

export type createRequestResponse = createRequestResponseSuccess | createRequestResponseError;

export const getCreateRequestUrl = () => {
	return `/enroll`;
};

/**
 * Submits a new enrollment request for processing.
 * @summary Create a new enrollment request
 */
export const createRequest = async (
	enrollRequestDTO: EnrollRequestDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<createRequestResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<createRequestResponse>(getCreateRequestUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(enrollRequestDTO)
	});
};

export const getCreateRequestMutationOptions = <
	TError = EnrollRequestDTO,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createRequest>>,
		TError,
		CreateRequestMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createRequest>>,
	TError,
	CreateRequestMutationVariables,
	TContext
> => {
	const mutationKey = ['createRequest'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createRequest>>,
		CreateRequestMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return createRequest(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createRequest>>>;
export type CreateRequestMutationBody = EnrollRequestDTO;
export type CreateRequestMutationError = EnrollRequestDTO;
export type CreateRequestMutationVariables = { data: EnrollRequestDTO };

/**
 * @summary Create a new enrollment request
 */
export const useCreateRequest = <TError = EnrollRequestDTO, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createRequest>>,
			TError,
			CreateRequestMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createRequest>>,
	TError,
	CreateRequestMutationVariables,
	TContext
> => {
	return useMutation(getCreateRequestMutationOptions(options), queryClient);
};
export type getOneRequestResponse200 = {
	data: EnrollRequestDTO;
	status: 200;
};

export type getOneRequestResponse404 = {
	data: EnrollRequestDTO;
	status: 404;
};

export type getOneRequestResponseSuccess = getOneRequestResponse200 & {
	headers: Headers;
};
export type getOneRequestResponseError = getOneRequestResponse404 & {
	headers: Headers;
};

export type getOneRequestResponse = getOneRequestResponseSuccess | getOneRequestResponseError;

export const getGetOneRequestUrl = (id: number) => {
	return `/enroll/${id}`;
};

/**
 * Retrieves a single enrollment request details.
 * @summary Get enrollment request by ID
 */
export const getOneRequest = async (
	id: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<getOneRequestResponse> => {
	return customFetch<getOneRequestResponse>(getGetOneRequestUrl(id), {
		...options,
		method: 'GET'
	});
};

export const getGetOneRequestQueryKey = (id: number) => {
	return [`/enroll/${id}`] as const;
};

export const getGetOneRequestQueryOptions = <
	TData = Awaited<ReturnType<typeof getOneRequest>>,
	TError = EnrollRequestDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOneRequestQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneRequest>>> = ({ signal }) =>
		getOneRequest(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: id !== null && id !== undefined,
		...queryOptions
	} as UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetOneRequestQueryResult = NonNullable<Awaited<ReturnType<typeof getOneRequest>>>;
export type GetOneRequestQueryError = EnrollRequestDTO;

export function useGetOneRequest<
	TData = Awaited<ReturnType<typeof getOneRequest>>,
	TError = EnrollRequestDTO
>(
	id: number,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneRequest>>,
					TError,
					Awaited<ReturnType<typeof getOneRequest>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneRequest<
	TData = Awaited<ReturnType<typeof getOneRequest>>,
	TError = EnrollRequestDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneRequest>>,
					TError,
					Awaited<ReturnType<typeof getOneRequest>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneRequest<
	TData = Awaited<ReturnType<typeof getOneRequest>>,
	TError = EnrollRequestDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get enrollment request by ID
 */

export function useGetOneRequest<
	TData = Awaited<ReturnType<typeof getOneRequest>>,
	TError = EnrollRequestDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneRequest>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetOneRequestQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type editOneRequestResponseDefault = {
	data: unknown;
	status: number;
};

export type editOneRequestResponseError = editOneRequestResponseDefault & {
	headers: Headers;
};

export type editOneRequestResponse = editOneRequestResponseError;

export const getEditOneRequestUrl = (id: number) => {
	return `/enroll/${id}`;
};

/**
 * Updates a specific enrollment request.
 * @summary Edit one enrollment request
 */
export const editOneRequest = async (
	id: number,
	enrollRequestDTO: EnrollRequestDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<editOneRequestResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<editOneRequestResponse>(getEditOneRequestUrl(id), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(enrollRequestDTO)
	});
};

export const getEditOneRequestMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editOneRequest>>,
		TError,
		EditOneRequestMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editOneRequest>>,
	TError,
	EditOneRequestMutationVariables,
	TContext
> => {
	const mutationKey = ['editOneRequest'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editOneRequest>>,
		EditOneRequestMutationVariables
	> = (props) => {
		const { id, data } = props ?? {};

		return editOneRequest(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditOneRequestMutationResult = NonNullable<Awaited<ReturnType<typeof editOneRequest>>>;
export type EditOneRequestMutationBody = EnrollRequestDTO;
export type EditOneRequestMutationError = unknown;
export type EditOneRequestMutationVariables = { id: number; data: EnrollRequestDTO };

/**
 * @summary Edit one enrollment request
 */
export const useEditOneRequest = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editOneRequest>>,
			TError,
			EditOneRequestMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof editOneRequest>>,
	TError,
	EditOneRequestMutationVariables,
	TContext
> => {
	return useMutation(getEditOneRequestMutationOptions(options), queryClient);
};
export type deleteOneEnrollRequestResponseDefault = {
	data: unknown;
	status: number;
};

export type deleteOneEnrollRequestResponseError = deleteOneEnrollRequestResponseDefault & {
	headers: Headers;
};

export type deleteOneEnrollRequestResponse = deleteOneEnrollRequestResponseError;

export const getDeleteOneEnrollRequestUrl = (id: number) => {
	return `/enroll/${id}`;
};

/**
 * Deletes a specific enrollment request.
 * @summary Delete one enrollment request
 */
export const deleteOneEnrollRequest = async (
	id: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<deleteOneEnrollRequestResponse> => {
	return customFetch<deleteOneEnrollRequestResponse>(getDeleteOneEnrollRequestUrl(id), {
		...options,
		method: 'DELETE'
	});
};

export const getDeleteOneEnrollRequestMutationOptions = <
	TError = unknown,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteOneEnrollRequest>>,
		TError,
		DeleteOneEnrollRequestMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteOneEnrollRequest>>,
	TError,
	DeleteOneEnrollRequestMutationVariables,
	TContext
> => {
	const mutationKey = ['deleteOneEnrollRequest'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteOneEnrollRequest>>,
		DeleteOneEnrollRequestMutationVariables
	> = (props) => {
		const { id } = props ?? {};

		return deleteOneEnrollRequest(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteOneEnrollRequestMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteOneEnrollRequest>>
>;

export type DeleteOneEnrollRequestMutationError = unknown;
export type DeleteOneEnrollRequestMutationVariables = { id: number };

/**
 * @summary Delete one enrollment request
 */
export const useDeleteOneEnrollRequest = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteOneEnrollRequest>>,
			TError,
			DeleteOneEnrollRequestMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteOneEnrollRequest>>,
	TError,
	DeleteOneEnrollRequestMutationVariables,
	TContext
> => {
	return useMutation(getDeleteOneEnrollRequestMutationOptions(options), queryClient);
};
export type getAllLogsResponseDefault = {
	data: unknown;
	status: number;
};

export type getAllLogsResponseError = getAllLogsResponseDefault & {
	headers: Headers;
};

export type getAllLogsResponse = getAllLogsResponseError;

export const getGetAllLogsUrl = () => {
	return `/enroll/logs`;
};

/**
 * Returns a list of all logs.
 * @summary Get all logs
 */
export const getAllLogs = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllLogsResponse> => {
	return customFetch<getAllLogsResponse>(getGetAllLogsUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllLogsQueryKey = () => {
	return [`/enroll/logs`] as const;
};

export const getGetAllLogsQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllLogs>>,
	TError = unknown
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllLogsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLogs>>> = ({ signal }) =>
		getAllLogs({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllLogs>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLogs>>>;
export type GetAllLogsQueryError = unknown;

export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllLogs>>,
					TError,
					Awaited<ReturnType<typeof getAllLogs>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllLogs>>,
					TError,
					Awaited<ReturnType<typeof getAllLogs>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all logs
 */

export function useGetAllLogs<TData = Awaited<ReturnType<typeof getAllLogs>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLogs>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllLogsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
