/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';
import type { FileDTO, PresignedLinkDTO } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === 'queryKey') continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key]
		});
	}
	return result;
};

export type getPressingUrlResponse200 = {
	data: PresignedLinkDTO;
	status: 200;
};

export type getPressingUrlResponseSuccess = getPressingUrlResponse200 & {
	headers: Headers;
};
export type getPressingUrlResponse = getPressingUrlResponseSuccess;

export const getGetPressingUrlUrl = () => {
	return `/file/url`;
};

/**
 * Creates a temporary, secure link to access the file content.
 * @summary Generate a presigned URL for a given file
 */
export const getPressingUrl = async (
	fileDTO: FileDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<getPressingUrlResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<getPressingUrlResponse>(getGetPressingUrlUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(fileDTO)
	});
};

export const getGetPressingUrlMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getPressingUrl>>,
		TError,
		GetPressingUrlMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getPressingUrl>>,
	TError,
	GetPressingUrlMutationVariables,
	TContext
> => {
	const mutationKey = ['getPressingUrl'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getPressingUrl>>,
		GetPressingUrlMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return getPressingUrl(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetPressingUrlMutationResult = NonNullable<Awaited<ReturnType<typeof getPressingUrl>>>;
export type GetPressingUrlMutationBody = FileDTO;
export type GetPressingUrlMutationError = unknown;
export type GetPressingUrlMutationVariables = { data: FileDTO };

/**
 * @summary Generate a presigned URL for a given file
 */
export const useGetPressingUrl = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getPressingUrl>>,
			TError,
			GetPressingUrlMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof getPressingUrl>>,
	TError,
	GetPressingUrlMutationVariables,
	TContext
> => {
	return useMutation(getGetPressingUrlMutationOptions(options), queryClient);
};
export type getAllFilesResponse200 = {
	data: FileDTO[];
	status: 200;
};

export type getAllFilesResponseSuccess = getAllFilesResponse200 & {
	headers: Headers;
};
export type getAllFilesResponse = getAllFilesResponseSuccess;

export const getGetAllFilesUrl = () => {
	return `/file`;
};

/**
 * Retrieves a collection of metadata for all stored files.
 * @summary List all available files
 */
export const getAllFiles = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllFilesResponse> => {
	return customFetch<getAllFilesResponse>(getGetAllFilesUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllFilesQueryKey = () => {
	return [`/file`] as const;
};

export const getGetAllFilesQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllFiles>>,
	TError = unknown
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllFilesQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllFiles>>> = ({ signal }) =>
		getAllFiles({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllFiles>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllFilesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllFiles>>>;
export type GetAllFilesQueryError = unknown;

export function useGetAllFiles<TData = Awaited<ReturnType<typeof getAllFiles>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllFiles>>,
					TError,
					Awaited<ReturnType<typeof getAllFiles>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllFiles<TData = Awaited<ReturnType<typeof getAllFiles>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllFiles>>,
					TError,
					Awaited<ReturnType<typeof getAllFiles>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllFiles<TData = Awaited<ReturnType<typeof getAllFiles>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all available files
 */

export function useGetAllFiles<TData = Awaited<ReturnType<typeof getAllFiles>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllFilesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type getFileResponse200 = {
	data: string;
	status: 200;
};

export type getFileResponseSuccess = getFileResponse200 & {
	headers: Headers;
};
export type getFileResponse = getFileResponseSuccess;

export const getGetFileUrl = (filename: string) => {
	return `/file/${filename}`;
};

/**
 * Fetches the raw content of a file given its name.
 * @summary Retrieve a file content by its filename
 */
export const getFile = async (
	filename: string,
	options?: Parameters<typeof customFetch>[1]
): Promise<getFileResponse> => {
	return customFetch<getFileResponse>(getGetFileUrl(filename), {
		...options,
		method: 'GET'
	});
};

export const getGetFileQueryKey = (filename: string) => {
	return [`/file/${filename}`] as const;
};

export const getGetFileQueryOptions = <
	TData = Awaited<ReturnType<typeof getFile>>,
	TError = unknown
>(
	filename: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetFileQueryKey(filename);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getFile>>> = ({ signal }) =>
		getFile(filename, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: filename !== null && filename !== undefined,
		...queryOptions
	} as UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetFileQueryResult = NonNullable<Awaited<ReturnType<typeof getFile>>>;
export type GetFileQueryError = unknown;

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = unknown>(
	filename: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getFile>>,
					TError,
					Awaited<ReturnType<typeof getFile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = unknown>(
	filename: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getFile>>,
					TError,
					Awaited<ReturnType<typeof getFile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = unknown>(
	filename: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieve a file content by its filename
 */

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = unknown>(
	filename: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetFileQueryOptions(filename, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
