import { SetStateAction, useState } from 'react';
import { VerticalNavigation } from '../vesticalNavigation/VerticalNavigation';
import Footer from './footer/Footer';
import Header from './header/Header';
import Head from 'next/head';
import { AccountBox, Analytics, Feed, Foundation } from '@mui/icons-material';

const pages = [
  {
    id: 1,
    text: 'Dashboard',
    path: '/admin',
    icon: <Analytics />
  },
  {
    id: 2,
    text: 'Projects',
    path: '/admin/projects',
    icon: <Foundation />
  },
  {
    id: 3,
    text: 'Updates',
    path: '/admin/updates',
    icon: <Feed />
  },
  {
    id: 4,
    text: 'Enroll Requests',
    path: '/admin/enroll',
    icon: <AccountBox />
  }
];

export const Layout = ({ isAdmin, children } : { isAdmin?: boolean, children: any}) => {
  const [open, setOpen] = useState<boolean>(isAdmin ? true : false);
  
  return (
    <div className="layout">
      <Head>
        <title>Cooperativa Giraldo Sem Pavor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
      { isAdmin ? <VerticalNavigation open={open} pages={pages} setOpen={setOpen} /> : <></>}
    </div>
  );
}

export default Layout;
