/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';
import type { AuthRequestDTO, UserInfoDAO, UserInfoDTO } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === 'queryKey') continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key]
		});
	}
	return result;
};

export type authenticateAndGetTokenResponse200 = {
	data: string;
	status: 200;
};

export type authenticateAndGetTokenResponseSuccess = authenticateAndGetTokenResponse200 & {
	headers: Headers;
};
export type authenticateAndGetTokenResponse = authenticateAndGetTokenResponseSuccess;

export const getAuthenticateAndGetTokenUrl = () => {
	return `/auth/generateToken`;
};

/**
 * Requires username and password.
 * @summary Authenticates user and generates a JWT token
 */
export const authenticateAndGetToken = async (
	authRequestDTO: AuthRequestDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<authenticateAndGetTokenResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<authenticateAndGetTokenResponse>(getAuthenticateAndGetTokenUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(authRequestDTO)
	});
};

export const getAuthenticateAndGetTokenMutationOptions = <
	TError = unknown,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authenticateAndGetToken>>,
		TError,
		AuthenticateAndGetTokenMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authenticateAndGetToken>>,
	TError,
	AuthenticateAndGetTokenMutationVariables,
	TContext
> => {
	const mutationKey = ['authenticateAndGetToken'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authenticateAndGetToken>>,
		AuthenticateAndGetTokenMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return authenticateAndGetToken(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthenticateAndGetTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof authenticateAndGetToken>>
>;
export type AuthenticateAndGetTokenMutationBody = AuthRequestDTO;
export type AuthenticateAndGetTokenMutationError = unknown;
export type AuthenticateAndGetTokenMutationVariables = { data: AuthRequestDTO };

/**
 * @summary Authenticates user and generates a JWT token
 */
export const useAuthenticateAndGetToken = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authenticateAndGetToken>>,
			TError,
			AuthenticateAndGetTokenMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof authenticateAndGetToken>>,
	TError,
	AuthenticateAndGetTokenMutationVariables,
	TContext
> => {
	return useMutation(getAuthenticateAndGetTokenMutationOptions(options), queryClient);
};
export type addNewUserResponse200 = {
	data: string;
	status: 200;
};

export type addNewUserResponseSuccess = addNewUserResponse200 & {
	headers: Headers;
};
export type addNewUserResponse = addNewUserResponseSuccess;

export const getAddNewUserUrl = () => {
	return `/auth/add`;
};

/**
 * Requires ADMIN role.
 * @summary Adds a new user to the system
 */
export const addNewUser = async (
	userInfoDAO: UserInfoDAO,
	options?: Parameters<typeof customFetch>[1]
): Promise<addNewUserResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<addNewUserResponse>(getAddNewUserUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(userInfoDAO)
	});
};

export const getAddNewUserMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof addNewUser>>,
		TError,
		AddNewUserMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof addNewUser>>,
	TError,
	AddNewUserMutationVariables,
	TContext
> => {
	const mutationKey = ['addNewUser'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof addNewUser>>,
		AddNewUserMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return addNewUser(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AddNewUserMutationResult = NonNullable<Awaited<ReturnType<typeof addNewUser>>>;
export type AddNewUserMutationBody = UserInfoDAO;
export type AddNewUserMutationError = unknown;
export type AddNewUserMutationVariables = { data: UserInfoDAO };

/**
 * @summary Adds a new user to the system
 */
export const useAddNewUser = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof addNewUser>>,
			TError,
			AddNewUserMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof addNewUser>>,
	TError,
	AddNewUserMutationVariables,
	TContext
> => {
	return useMutation(getAddNewUserMutationOptions(options), queryClient);
};
export type userProfileResponse200 = {
	data: UserInfoDTO;
	status: 200;
};

export type userProfileResponseSuccess = userProfileResponse200 & {
	headers: Headers;
};
export type userProfileResponse = userProfileResponseSuccess;

export const getUserProfileUrl = (username: string) => {
	return `/auth/user/${username}`;
};

/**
 * Requires ADMIN role.
 * @summary Retrieves a user's profile by username
 */
export const userProfile = async (
	username: string,
	options?: Parameters<typeof customFetch>[1]
): Promise<userProfileResponse> => {
	return customFetch<userProfileResponse>(getUserProfileUrl(username), {
		...options,
		method: 'GET'
	});
};

export const getUserProfileQueryKey = (username: string) => {
	return [`/auth/user/${username}`] as const;
};

export const getUserProfileQueryOptions = <
	TData = Awaited<ReturnType<typeof userProfile>>,
	TError = unknown
>(
	username: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserProfileQueryKey(username);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userProfile>>> = ({ signal }) =>
		userProfile(username, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: username !== null && username !== undefined,
		...queryOptions
	} as UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type UserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userProfile>>>;
export type UserProfileQueryError = unknown;

export function useUserProfile<TData = Awaited<ReturnType<typeof userProfile>>, TError = unknown>(
	username: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof userProfile>>,
					TError,
					Awaited<ReturnType<typeof userProfile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserProfile<TData = Awaited<ReturnType<typeof userProfile>>, TError = unknown>(
	username: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof userProfile>>,
					TError,
					Awaited<ReturnType<typeof userProfile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserProfile<TData = Awaited<ReturnType<typeof userProfile>>, TError = unknown>(
	username: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieves a user's profile by username
 */

export function useUserProfile<TData = Awaited<ReturnType<typeof userProfile>>, TError = unknown>(
	username: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getUserProfileQueryOptions(username, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type adminProfileResponse200 = {
	data: string;
	status: 200;
};

export type adminProfileResponseSuccess = adminProfileResponse200 & {
	headers: Headers;
};
export type adminProfileResponse = adminProfileResponseSuccess;

export const getAdminProfileUrl = () => {
	return `/auth/admin/profile`;
};

/**
 * Requires ADMIN role.
 * @summary Retrieves the admin's profile information
 */
export const adminProfile = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<adminProfileResponse> => {
	return customFetch<adminProfileResponse>(getAdminProfileUrl(), {
		...options,
		method: 'GET'
	});
};

export const getAdminProfileQueryKey = () => {
	return [`/auth/admin/profile`] as const;
};

export const getAdminProfileQueryOptions = <
	TData = Awaited<ReturnType<typeof adminProfile>>,
	TError = unknown
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminProfile>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAdminProfileQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof adminProfile>>> = ({ signal }) =>
		adminProfile({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof adminProfile>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminProfileQueryResult = NonNullable<Awaited<ReturnType<typeof adminProfile>>>;
export type AdminProfileQueryError = unknown;

export function useAdminProfile<TData = Awaited<ReturnType<typeof adminProfile>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminProfile>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof adminProfile>>,
					TError,
					Awaited<ReturnType<typeof adminProfile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminProfile<TData = Awaited<ReturnType<typeof adminProfile>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminProfile>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof adminProfile>>,
					TError,
					Awaited<ReturnType<typeof adminProfile>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAdminProfile<TData = Awaited<ReturnType<typeof adminProfile>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieves the admin's profile information
 */

export function useAdminProfile<TData = Awaited<ReturnType<typeof adminProfile>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof adminProfile>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getAdminProfileQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
