import { describe, expect, it, vi } from 'vitest';

import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { Gallery } from './Gallery';

// next/image is globally mocked in vitest.setup.ts → renders as <img>

const mockImages = [
	{ id: '1', url: '/image1.jpg' },
	{ id: '2', url: '/image2.jpg' },
	{ id: '3', url: '/image3.jpg' }
];

describe('Gallery', () => {
	it('renders one thumbnail button per image', () => {
		render(<Gallery images={mockImages} currentIndex={0} />);

		expect(screen.getAllByRole('button')).toHaveLength(mockImages.length);
	});

	it('renders a thumbnail image with the correct alt text for each image', () => {
		render(<Gallery images={mockImages} currentIndex={0} />);

		expect(screen.getByAltText('Thumbnail 1')).toBeDefined();
		expect(screen.getByAltText('Thumbnail 2')).toBeDefined();
		expect(screen.getByAltText('Thumbnail 3')).toBeDefined();
	});

	it('calls onSelectImage with the correct index when a thumbnail is clicked', async () => {
		const onSelectImage = vi.fn();
		render(<Gallery images={mockImages} currentIndex={0} onSelectImage={onSelectImage} />);

		const buttons = screen.getAllByRole('button');
		await userEvent.click(buttons[1]);

		expect(onSelectImage).toHaveBeenCalledTimes(1);
		expect(onSelectImage).toHaveBeenCalledWith(1);
	});

	it('calls onSelectImage with index 0 when the first thumbnail is clicked', async () => {
		const onSelectImage = vi.fn();
		render(<Gallery images={mockImages} currentIndex={2} onSelectImage={onSelectImage} />);

		const buttons = screen.getAllByRole('button');
		await userEvent.click(buttons[0]);

		expect(onSelectImage).toHaveBeenCalledWith(0);
	});

	it('does not throw when onSelectImage is not provided and a thumbnail is clicked', async () => {
		render(<Gallery images={mockImages} currentIndex={0} />);

		const buttons = screen.getAllByRole('button');
		await userEvent.click(buttons[0]);

		// No error thrown → test passes
	});

	it('applies horizontal gallery class when vertical is false', () => {
		const { container } = render(<Gallery images={mockImages} currentIndex={0} vertical={false} />);

		// The first child div is the gallery container
		const galleryDiv = container.firstChild as HTMLElement;
		// The class name is generated by emotion css; just check it's present
		expect(galleryDiv.className.length).toBeGreaterThan(0);
	});

	it('applies a different class when vertical=true vs vertical=false', () => {
		const { container: horizontal } = render(
			<Gallery images={mockImages} currentIndex={0} vertical={false} />
		);
		const { container: vertical } = render(
			<Gallery images={mockImages} currentIndex={0} vertical={true} />
		);

		const horizontalClass = (horizontal.firstChild as HTMLElement).className;
		const verticalClass = (vertical.firstChild as HTMLElement).className;

		expect(verticalClass).not.toBe(horizontalClass);
	});

	it('sets translateX transform on the indicator for horizontal layout', () => {
		// currentIndex=1, THUMBNAIL_STEP=88 → translateX(88px)
		const { container } = render(<Gallery images={mockImages} currentIndex={1} vertical={false} />);

		const indicator = container.querySelector('[style*="translateX"]') as HTMLElement;
		expect(indicator).not.toBeNull();
		expect(indicator.style.transform).toBe('translateX(88px)');
	});

	it('sets translateY transform on the indicator for vertical layout', () => {
		// currentIndex=1, THUMBNAIL_STEP=88 → translateY(88px)
		const { container } = render(<Gallery images={mockImages} currentIndex={1} vertical={true} />);

		const indicator = container.querySelector('[style*="translateY"]') as HTMLElement;
		expect(indicator).not.toBeNull();
		expect(indicator.style.transform).toBe('translateY(88px)');
	});
});
