/* eslint-disable react/prop-types */
import Footer from './layout/footer/Footer';
import Header from './layout/header/Header';
import Head from 'next/head';

export default function Layout({ children }) {
  return (
    <div className="layout">
      <Head>
        <title>Cooperativa Giraldo Sem Pavor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
