/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';
import type { ProjectDTO, ProjectListItemDTO, ProjectPriorityDTO } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === 'queryKey') continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key]
		});
	}
	return result;
};

export type updateProjectResponse200 = {
	data: ProjectDTO;
	status: 200;
};

export type updateProjectResponse404 = {
	data: ProjectDTO;
	status: 404;
};

export type updateProjectResponseSuccess = updateProjectResponse200 & {
	headers: Headers;
};
export type updateProjectResponseError = updateProjectResponse404 & {
	headers: Headers;
};

export type updateProjectResponse = updateProjectResponseSuccess | updateProjectResponseError;

export const getUpdateProjectUrl = (projectId: number) => {
	return `/project/${projectId}`;
};

/**
 * Updates all details of a specified project by ID.
 * @summary Update an existing project
 */
export const updateProject = async (
	projectId: number,
	projectDTO: ProjectDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<updateProjectResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<updateProjectResponse>(getUpdateProjectUrl(projectId), {
		...options,
		method: 'PUT',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(projectDTO)
	});
};

export const getUpdateProjectMutationOptions = <TError = ProjectDTO, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateProject>>,
		TError,
		UpdateProjectMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateProject>>,
	TError,
	UpdateProjectMutationVariables,
	TContext
> => {
	const mutationKey = ['updateProject'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateProject>>,
		UpdateProjectMutationVariables
	> = (props) => {
		const { projectId, data } = props ?? {};

		return updateProject(projectId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>;
export type UpdateProjectMutationBody = ProjectDTO;
export type UpdateProjectMutationError = ProjectDTO;
export type UpdateProjectMutationVariables = { projectId: number; data: ProjectDTO };

/**
 * @summary Update an existing project
 */
export const useUpdateProject = <TError = ProjectDTO, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateProject>>,
			TError,
			UpdateProjectMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updateProject>>,
	TError,
	UpdateProjectMutationVariables,
	TContext
> => {
	return useMutation(getUpdateProjectMutationOptions(options), queryClient);
};
export type deleteProjectResponse204 = {
	data: void;
	status: 204;
};

export type deleteProjectResponse404 = {
	data: void;
	status: 404;
};

export type deleteProjectResponseSuccess = deleteProjectResponse204 & {
	headers: Headers;
};
export type deleteProjectResponseError = deleteProjectResponse404 & {
	headers: Headers;
};

export type deleteProjectResponse = deleteProjectResponseSuccess | deleteProjectResponseError;

export const getDeleteProjectUrl = (projectId: number) => {
	return `/project/${projectId}`;
};

/**
 * Deletes a project by its ID.
 * @summary Delete a project
 */
export const deleteProject = async (
	projectId: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<deleteProjectResponse> => {
	return customFetch<deleteProjectResponse>(getDeleteProjectUrl(projectId), {
		...options,
		method: 'DELETE'
	});
};

export const getDeleteProjectMutationOptions = <TError = void, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteProject>>,
		TError,
		DeleteProjectMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteProject>>,
	TError,
	DeleteProjectMutationVariables,
	TContext
> => {
	const mutationKey = ['deleteProject'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteProject>>,
		DeleteProjectMutationVariables
	> = (props) => {
		const { projectId } = props ?? {};

		return deleteProject(projectId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>;

export type DeleteProjectMutationError = void;
export type DeleteProjectMutationVariables = { projectId: number };

/**
 * @summary Delete a project
 */
export const useDeleteProject = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteProject>>,
			TError,
			DeleteProjectMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteProject>>,
	TError,
	DeleteProjectMutationVariables,
	TContext
> => {
	return useMutation(getDeleteProjectMutationOptions(options), queryClient);
};
export type getAllProjectsResponse200 = {
	data: ProjectListItemDTO[];
	status: 200;
};

export type getAllProjectsResponse401 = {
	data: ProjectListItemDTO[];
	status: 401;
};

export type getAllProjectsResponseSuccess = getAllProjectsResponse200 & {
	headers: Headers;
};
export type getAllProjectsResponseError = getAllProjectsResponse401 & {
	headers: Headers;
};

export type getAllProjectsResponse = getAllProjectsResponseSuccess | getAllProjectsResponseError;

export const getGetAllProjectsUrl = () => {
	return `/project`;
};

/**
 * Retrieves a list of all available projects.
 * @summary Get all projects
 */
export const getAllProjects = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllProjectsResponse> => {
	return customFetch<getAllProjectsResponse>(getGetAllProjectsUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllProjectsQueryKey = () => {
	return [`/project`] as const;
};

export const getGetAllProjectsQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllProjects>>,
	TError = ProjectListItemDTO[]
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProjects>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllProjectsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProjects>>> = ({ signal }) =>
		getAllProjects({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllProjects>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProjects>>>;
export type GetAllProjectsQueryError = ProjectListItemDTO[];

export function useGetAllProjects<
	TData = Awaited<ReturnType<typeof getAllProjects>>,
	TError = ProjectListItemDTO[]
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProjects>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjects>>,
					TError,
					Awaited<ReturnType<typeof getAllProjects>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjects<
	TData = Awaited<ReturnType<typeof getAllProjects>>,
	TError = ProjectListItemDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProjects>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjects>>,
					TError,
					Awaited<ReturnType<typeof getAllProjects>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjects<
	TData = Awaited<ReturnType<typeof getAllProjects>>,
	TError = ProjectListItemDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProjects>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all projects
 */

export function useGetAllProjects<
	TData = Awaited<ReturnType<typeof getAllProjects>>,
	TError = ProjectListItemDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProjects>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllProjectsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type createProjectResponse200 = {
	data: ProjectDTO;
	status: 200;
};

export type createProjectResponseSuccess = createProjectResponse200 & {
	headers: Headers;
};
export type createProjectResponse = createProjectResponseSuccess;

export const getCreateProjectUrl = () => {
	return `/project`;
};

/**
 * Creates and saves a new project record.
 * @summary Create a new project
 */
export const createProject = async (
	projectDTO: ProjectDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<createProjectResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<createProjectResponse>(getCreateProjectUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(projectDTO)
	});
};

export const getCreateProjectMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createProject>>,
		TError,
		CreateProjectMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createProject>>,
	TError,
	CreateProjectMutationVariables,
	TContext
> => {
	const mutationKey = ['createProject'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createProject>>,
		CreateProjectMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return createProject(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>;
export type CreateProjectMutationBody = ProjectDTO;
export type CreateProjectMutationError = unknown;
export type CreateProjectMutationVariables = { data: ProjectDTO };

/**
 * @summary Create a new project
 */
export const useCreateProject = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createProject>>,
			TError,
			CreateProjectMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createProject>>,
	TError,
	CreateProjectMutationVariables,
	TContext
> => {
	return useMutation(getCreateProjectMutationOptions(options), queryClient);
};
export type getOneProjectResponse200 = {
	data: ProjectDTO;
	status: 200;
};

export type getOneProjectResponse404 = {
	data: ProjectDTO;
	status: 404;
};

export type getOneProjectResponseSuccess = getOneProjectResponse200 & {
	headers: Headers;
};
export type getOneProjectResponseError = getOneProjectResponse404 & {
	headers: Headers;
};

export type getOneProjectResponse = getOneProjectResponseSuccess | getOneProjectResponseError;

export const getGetOneProjectUrl = (id: number) => {
	return `/project/${id}`;
};

/**
 * Retrieves a single project by its unique identifier.
 * @summary Get project by ID
 */
export const getOneProject = async (
	id: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<getOneProjectResponse> => {
	return customFetch<getOneProjectResponse>(getGetOneProjectUrl(id), {
		...options,
		method: 'GET'
	});
};

export const getGetOneProjectQueryKey = (id: number) => {
	return [`/project/${id}`] as const;
};

export const getGetOneProjectQueryOptions = <
	TData = Awaited<ReturnType<typeof getOneProject>>,
	TError = ProjectDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOneProjectQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneProject>>> = ({ signal }) =>
		getOneProject(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: id !== null && id !== undefined,
		...queryOptions
	} as UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetOneProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getOneProject>>>;
export type GetOneProjectQueryError = ProjectDTO;

export function useGetOneProject<
	TData = Awaited<ReturnType<typeof getOneProject>>,
	TError = ProjectDTO
>(
	id: number,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneProject>>,
					TError,
					Awaited<ReturnType<typeof getOneProject>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneProject<
	TData = Awaited<ReturnType<typeof getOneProject>>,
	TError = ProjectDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneProject>>,
					TError,
					Awaited<ReturnType<typeof getOneProject>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneProject<
	TData = Awaited<ReturnType<typeof getOneProject>>,
	TError = ProjectDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get project by ID
 */

export function useGetOneProject<
	TData = Awaited<ReturnType<typeof getOneProject>>,
	TError = ProjectDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneProject>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetOneProjectQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type editOneProjectResponse200 = {
	data: ProjectDTO;
	status: 200;
};

export type editOneProjectResponseSuccess = editOneProjectResponse200 & {
	headers: Headers;
};
export type editOneProjectResponse = editOneProjectResponseSuccess;

export const getEditOneProjectUrl = (id: number) => {
	return `/project/${id}`;
};

export const editOneProject = async (
	id: number,
	projectDTO: ProjectDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<editOneProjectResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<editOneProjectResponse>(getEditOneProjectUrl(id), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(projectDTO)
	});
};

export const getEditOneProjectMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editOneProject>>,
		TError,
		EditOneProjectMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editOneProject>>,
	TError,
	EditOneProjectMutationVariables,
	TContext
> => {
	const mutationKey = ['editOneProject'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editOneProject>>,
		EditOneProjectMutationVariables
	> = (props) => {
		const { id, data } = props ?? {};

		return editOneProject(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditOneProjectMutationResult = NonNullable<Awaited<ReturnType<typeof editOneProject>>>;
export type EditOneProjectMutationBody = ProjectDTO;
export type EditOneProjectMutationError = unknown;
export type EditOneProjectMutationVariables = { id: number; data: ProjectDTO };

export const useEditOneProject = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editOneProject>>,
			TError,
			EditOneProjectMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof editOneProject>>,
	TError,
	EditOneProjectMutationVariables,
	TContext
> => {
	return useMutation(getEditOneProjectMutationOptions(options), queryClient);
};
export type updatePriorityResponse200 = {
	data: ProjectPriorityDTO[];
	status: 200;
};

export type updatePriorityResponseSuccess = updatePriorityResponse200 & {
	headers: Headers;
};
export type updatePriorityResponse = updatePriorityResponseSuccess;

export const getUpdatePriorityUrl = () => {
	return `/project/priority`;
};

export const updatePriority = async (
	projectPriorityDTO: ProjectPriorityDTO[],
	options?: Parameters<typeof customFetch>[1]
): Promise<updatePriorityResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<updatePriorityResponse>(getUpdatePriorityUrl(), {
		...options,
		method: 'PATCH',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(projectPriorityDTO)
	});
};

export const getUpdatePriorityMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updatePriority>>,
		TError,
		UpdatePriorityMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updatePriority>>,
	TError,
	UpdatePriorityMutationVariables,
	TContext
> => {
	const mutationKey = ['updatePriority'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updatePriority>>,
		UpdatePriorityMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return updatePriority(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdatePriorityMutationResult = NonNullable<Awaited<ReturnType<typeof updatePriority>>>;
export type UpdatePriorityMutationBody = ProjectPriorityDTO[];
export type UpdatePriorityMutationError = unknown;
export type UpdatePriorityMutationVariables = { data: ProjectPriorityDTO[] };

export const useUpdatePriority = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updatePriority>>,
			TError,
			UpdatePriorityMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updatePriority>>,
	TError,
	UpdatePriorityMutationVariables,
	TContext
> => {
	return useMutation(getUpdatePriorityMutationOptions(options), queryClient);
};
export type getAllProjectsHistoryResponse200 = {
	data: ProjectListItemDTO[];
	status: 200;
};

export type getAllProjectsHistoryResponseSuccess = getAllProjectsHistoryResponse200 & {
	headers: Headers;
};
export type getAllProjectsHistoryResponse = getAllProjectsHistoryResponseSuccess;

export const getGetAllProjectsHistoryUrl = () => {
	return `/project/history`;
};

/**
 * Retrieves historical projects. Authenticated users receive detailed projects; anonymous users receive public project data.
 * @summary Get project history
 */
export const getAllProjectsHistory = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllProjectsHistoryResponse> => {
	return customFetch<getAllProjectsHistoryResponse>(getGetAllProjectsHistoryUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllProjectsHistoryQueryKey = () => {
	return [`/project/history`] as const;
};

export const getGetAllProjectsHistoryQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllProjectsHistory>>,
	TError = unknown
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsHistory>>, TError, TData>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllProjectsHistoryQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProjectsHistory>>> = ({ signal }) =>
		getAllProjectsHistory({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllProjectsHistory>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllProjectsHistoryQueryResult = NonNullable<
	Awaited<ReturnType<typeof getAllProjectsHistory>>
>;
export type GetAllProjectsHistoryQueryError = unknown;

export function useGetAllProjectsHistory<
	TData = Awaited<ReturnType<typeof getAllProjectsHistory>>,
	TError = unknown
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsHistory>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjectsHistory>>,
					TError,
					Awaited<ReturnType<typeof getAllProjectsHistory>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjectsHistory<
	TData = Awaited<ReturnType<typeof getAllProjectsHistory>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsHistory>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjectsHistory>>,
					TError,
					Awaited<ReturnType<typeof getAllProjectsHistory>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjectsHistory<
	TData = Awaited<ReturnType<typeof getAllProjectsHistory>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsHistory>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get project history
 */

export function useGetAllProjectsHistory<
	TData = Awaited<ReturnType<typeof getAllProjectsHistory>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsHistory>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllProjectsHistoryQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type getAllProjectsCurrentResponse200 = {
	data: ProjectListItemDTO[];
	status: 200;
};

export type getAllProjectsCurrentResponseSuccess = getAllProjectsCurrentResponse200 & {
	headers: Headers;
};
export type getAllProjectsCurrentResponse = getAllProjectsCurrentResponseSuccess;

export const getGetAllProjectsCurrentUrl = () => {
	return `/project/current`;
};

/**
 * Retrieves all current projects. Authenticated users receive detailed projects; anonymous users receive public project data.
 * @summary Get current projects
 */
export const getAllProjectsCurrent = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllProjectsCurrentResponse> => {
	return customFetch<getAllProjectsCurrentResponse>(getGetAllProjectsCurrentUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllProjectsCurrentQueryKey = () => {
	return [`/project/current`] as const;
};

export const getGetAllProjectsCurrentQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllProjectsCurrent>>,
	TError = unknown
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsCurrent>>, TError, TData>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllProjectsCurrentQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProjectsCurrent>>> = ({ signal }) =>
		getAllProjectsCurrent({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllProjectsCurrent>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllProjectsCurrentQueryResult = NonNullable<
	Awaited<ReturnType<typeof getAllProjectsCurrent>>
>;
export type GetAllProjectsCurrentQueryError = unknown;

export function useGetAllProjectsCurrent<
	TData = Awaited<ReturnType<typeof getAllProjectsCurrent>>,
	TError = unknown
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsCurrent>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjectsCurrent>>,
					TError,
					Awaited<ReturnType<typeof getAllProjectsCurrent>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjectsCurrent<
	TData = Awaited<ReturnType<typeof getAllProjectsCurrent>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsCurrent>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllProjectsCurrent>>,
					TError,
					Awaited<ReturnType<typeof getAllProjectsCurrent>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllProjectsCurrent<
	TData = Awaited<ReturnType<typeof getAllProjectsCurrent>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsCurrent>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current projects
 */

export function useGetAllProjectsCurrent<
	TData = Awaited<ReturnType<typeof getAllProjectsCurrent>>,
	TError = unknown
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getAllProjectsCurrent>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllProjectsCurrentQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
