/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { EnrollRequestStatusDTOStatus } from './enrollRequestStatusDTOStatus';

export interface EnrollRequestStatusDTO {
	status?: EnrollRequestStatusDTOStatus;
}
