/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { EnrollRequestLogsDTO } from './enrollRequestLogsDTO';

export interface EnrollRequestDTO {
	id?: string;
	firstName?: string;
	lastName?: string;
	telephoneNumber?: string;
	email?: string;
	projectId?: string;
	status?: string;
	subscribedUpdates?: boolean;
	createdOn?: string;
	logs?: EnrollRequestLogsDTO[];
}
