/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export type EnrollRequestStatusDTOStatus =
	(typeof EnrollRequestStatusDTOStatus)[keyof typeof EnrollRequestStatusDTOStatus];

export const EnrollRequestStatusDTOStatus = {
	Waiting: 'Waiting',
	Approved: 'Approved',
	Refused: 'Refused'
} as const;
