/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export type ProjectDTOAssignmentStatus =
	(typeof ProjectDTOAssignmentStatus)[keyof typeof ProjectDTOAssignmentStatus];

export const ProjectDTOAssignmentStatus = {
	WAITING: 'WAITING',
	ONGOING: 'ONGOING',
	CONCLUDED: 'CONCLUDED'
} as const;
