/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { EnrollRequestDTO } from './enrollRequestDTO';
import type { FileDTO } from './fileDTO';
import type { ProjectDTOAssignmentStatus } from './projectDTOAssignmentStatus';
import type { ProjectDTOConstructionStatus } from './projectDTOConstructionStatus';
import type { TypologyDetailsDTO } from './typologyDetailsDTO';
import type { UpdateDTO } from './updateDTO';

export interface ProjectDTO {
	id?: string;
	title?: string;
	assignmentStatus?: ProjectDTOAssignmentStatus;
	constructionStatus?: ProjectDTOConstructionStatus;
	district?: string;
	county?: string;
	lots?: number;
	assignedLots?: number;
	coordinates?: number[];
	coverPhoto?: FileDTO;
	files?: FileDTO[];
	enrollRequests?: EnrollRequestDTO[];
	typologies?: TypologyDetailsDTO[];
	updates?: UpdateDTO[];
	createdOn?: string;
	priority?: number;
}
