/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export type ProjectDTOConstructionStatus =
	(typeof ProjectDTOConstructionStatus)[keyof typeof ProjectDTOConstructionStatus];

export const ProjectDTOConstructionStatus = {
	ALLOTMENTPERMIT: 'ALLOTMENTPERMIT',
	BUILDINGPERMIT: 'BUILDINGPERMIT',
	CONCLUDED: 'CONCLUDED'
} as const;
