/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { ProjectDTO } from './projectDTO';
import type { PublicProjectDTO } from './publicProjectDTO';

export type ProjectListItemDTO = ProjectDTO | PublicProjectDTO;
