/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export type PublicProjectDTOConstructionStatus =
	(typeof PublicProjectDTOConstructionStatus)[keyof typeof PublicProjectDTOConstructionStatus];

export const PublicProjectDTOConstructionStatus = {
	ALLOTMENTPERMIT: 'ALLOTMENTPERMIT',
	BUILDINGPERMIT: 'BUILDINGPERMIT',
	CONCLUDED: 'CONCLUDED'
} as const;
