/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { FileDTO } from './fileDTO';
import type { PublicProjectDTOAssignmentStatus } from './publicProjectDTOAssignmentStatus';
import type { PublicProjectDTOConstructionStatus } from './publicProjectDTOConstructionStatus';
import type { TypologyDetailsDTO } from './typologyDetailsDTO';
import type { UpdateDTO } from './updateDTO';

export interface PublicProjectDTO {
	id?: string;
	title?: string;
	assignmentStatus?: PublicProjectDTOAssignmentStatus;
	constructionStatus?: PublicProjectDTOConstructionStatus;
	district?: string;
	county?: string;
	lots?: number;
	assignedLots?: number;
	coordinates?: number[];
	coverPhoto?: FileDTO;
	files?: FileDTO[];
	enrollRequestsCount?: number;
	typologies?: TypologyDetailsDTO[];
	updates?: UpdateDTO[];
	createdOn?: string;
	priority?: number;
}
