/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export type PublicProjectDTOAssignmentStatus =
	(typeof PublicProjectDTOAssignmentStatus)[keyof typeof PublicProjectDTOAssignmentStatus];

export const PublicProjectDTOAssignmentStatus = {
	WAITING: 'WAITING',
	ONGOING: 'ONGOING',
	CONCLUDED: 'CONCLUDED'
} as const;
