/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { FileDTO } from './fileDTO';

export interface TypologyDetailsDTO {
	id?: string;
	typology?: string;
	type?: string;
	bedroomNumber?: number;
	bathroomNumber?: number;
	garageNumber?: number;
	totalLotArea?: number;
	livingArea?: number;
	price?: number;
	plant?: FileDTO;
	lots?: number;
	assignedLots?: number;
}
