/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import type { FileDTO } from './fileDTO';
import type { UpdateProjectDTO } from './updateProjectDTO';

export interface UpdateDTO {
	id?: string;
	title?: string;
	content?: string;
	project?: UpdateProjectDTO;
	createdOn?: string;
	files?: FileDTO[];
	projectId?: number;
}
