/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */

export interface UserInfoDAO {
	name?: string;
	email?: string;
	password?: string;
	roles?: string;
}
