/**
 * Generated by orval 🍺
 * Do not edit manually.
 * CGSP API
 * CGSP Back-End REST API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';
import type { JsonNode, UpdateDTO } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === 'queryKey') continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key]
		});
	}
	return result;
};

export type getAllUpdatesResponse200 = {
	data: UpdateDTO[];
	status: 200;
};

export type getAllUpdatesResponse404 = {
	data: UpdateDTO[];
	status: 404;
};

export type getAllUpdatesResponseSuccess = getAllUpdatesResponse200 & {
	headers: Headers;
};
export type getAllUpdatesResponseError = getAllUpdatesResponse404 & {
	headers: Headers;
};

export type getAllUpdatesResponse = getAllUpdatesResponseSuccess | getAllUpdatesResponseError;

export const getGetAllUpdatesUrl = () => {
	return `/update`;
};

/**
 * Returns a list of all recorded updates.
 * @summary Retrieve all updates
 */
export const getAllUpdates = async (
	options?: Parameters<typeof customFetch>[1]
): Promise<getAllUpdatesResponse> => {
	return customFetch<getAllUpdatesResponse>(getGetAllUpdatesUrl(), {
		...options,
		method: 'GET'
	});
};

export const getGetAllUpdatesQueryKey = () => {
	return [`/update`] as const;
};

export const getGetAllUpdatesQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllUpdates>>,
	TError = UpdateDTO[]
>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUpdates>>, TError, TData>>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetAllUpdatesQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUpdates>>> = ({ signal }) =>
		getAllUpdates({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllUpdates>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllUpdatesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUpdates>>>;
export type GetAllUpdatesQueryError = UpdateDTO[];

export function useGetAllUpdates<
	TData = Awaited<ReturnType<typeof getAllUpdates>>,
	TError = UpdateDTO[]
>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUpdates>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllUpdates>>,
					TError,
					Awaited<ReturnType<typeof getAllUpdates>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllUpdates<
	TData = Awaited<ReturnType<typeof getAllUpdates>>,
	TError = UpdateDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUpdates>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllUpdates>>,
					TError,
					Awaited<ReturnType<typeof getAllUpdates>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllUpdates<
	TData = Awaited<ReturnType<typeof getAllUpdates>>,
	TError = UpdateDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUpdates>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieve all updates
 */

export function useGetAllUpdates<
	TData = Awaited<ReturnType<typeof getAllUpdates>>,
	TError = UpdateDTO[]
>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUpdates>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetAllUpdatesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type createUpdateResponse200 = {
	data: UpdateDTO;
	status: 200;
};

export type createUpdateResponse400 = {
	data: UpdateDTO;
	status: 400;
};

export type createUpdateResponseSuccess = createUpdateResponse200 & {
	headers: Headers;
};
export type createUpdateResponseError = createUpdateResponse400 & {
	headers: Headers;
};

export type createUpdateResponse = createUpdateResponseSuccess | createUpdateResponseError;

export const getCreateUpdateUrl = () => {
	return `/update`;
};

/**
 * Creates a new update entry. Requires role ADMIN.
 * @summary Create a new update record
 */
export const createUpdate = async (
	updateDTO: UpdateDTO,
	options?: Parameters<typeof customFetch>[1]
): Promise<createUpdateResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<createUpdateResponse>(getCreateUpdateUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(updateDTO)
	});
};

export const getCreateUpdateMutationOptions = <TError = UpdateDTO, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createUpdate>>,
		TError,
		CreateUpdateMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createUpdate>>,
	TError,
	CreateUpdateMutationVariables,
	TContext
> => {
	const mutationKey = ['createUpdate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createUpdate>>,
		CreateUpdateMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return createUpdate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof createUpdate>>>;
export type CreateUpdateMutationBody = UpdateDTO;
export type CreateUpdateMutationError = UpdateDTO;
export type CreateUpdateMutationVariables = { data: UpdateDTO };

/**
 * @summary Create a new update record
 */
export const useCreateUpdate = <TError = UpdateDTO, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createUpdate>>,
			TError,
			CreateUpdateMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createUpdate>>,
	TError,
	CreateUpdateMutationVariables,
	TContext
> => {
	return useMutation(getCreateUpdateMutationOptions(options), queryClient);
};
export type getOneUpdateResponse200 = {
	data: UpdateDTO;
	status: 200;
};

export type getOneUpdateResponse404 = {
	data: UpdateDTO;
	status: 404;
};

export type getOneUpdateResponseSuccess = getOneUpdateResponse200 & {
	headers: Headers;
};
export type getOneUpdateResponseError = getOneUpdateResponse404 & {
	headers: Headers;
};

export type getOneUpdateResponse = getOneUpdateResponseSuccess | getOneUpdateResponseError;

export const getGetOneUpdateUrl = (id: number) => {
	return `/update/${id}`;
};

/**
 * Fetches the details of an update record using its unique identifier.
 * @summary Retrieve a single update by ID
 */
export const getOneUpdate = async (
	id: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<getOneUpdateResponse> => {
	return customFetch<getOneUpdateResponse>(getGetOneUpdateUrl(id), {
		...options,
		method: 'GET'
	});
};

export const getGetOneUpdateQueryKey = (id: number) => {
	return [`/update/${id}`] as const;
};

export const getGetOneUpdateQueryOptions = <
	TData = Awaited<ReturnType<typeof getOneUpdate>>,
	TError = UpdateDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	}
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOneUpdateQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneUpdate>>> = ({ signal }) =>
		getOneUpdate(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: id !== null && id !== undefined,
		...queryOptions
	} as UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetOneUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof getOneUpdate>>>;
export type GetOneUpdateQueryError = UpdateDTO;

export function useGetOneUpdate<
	TData = Awaited<ReturnType<typeof getOneUpdate>>,
	TError = UpdateDTO
>(
	id: number,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneUpdate>>,
					TError,
					Awaited<ReturnType<typeof getOneUpdate>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneUpdate<
	TData = Awaited<ReturnType<typeof getOneUpdate>>,
	TError = UpdateDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOneUpdate>>,
					TError,
					Awaited<ReturnType<typeof getOneUpdate>>
				>,
				'initialData'
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOneUpdate<
	TData = Awaited<ReturnType<typeof getOneUpdate>>,
	TError = UpdateDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Retrieve a single update by ID
 */

export function useGetOneUpdate<
	TData = Awaited<ReturnType<typeof getOneUpdate>>,
	TError = UpdateDTO
>(
	id: number,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOneUpdate>>, TError, TData>>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetOneUpdateQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export type deleteOneUpdateResponse200 = {
	data: void;
	status: 200;
};

export type deleteOneUpdateResponseSuccess = deleteOneUpdateResponse200 & {
	headers: Headers;
};
export type deleteOneUpdateResponse = deleteOneUpdateResponseSuccess;

export const getDeleteOneUpdateUrl = (id: number) => {
	return `/update/${id}`;
};

/**
 * Deletes an update entry. Requires role ADMIN.
 * @summary Delete an update record by ID
 */
export const deleteOneUpdate = async (
	id: number,
	options?: Parameters<typeof customFetch>[1]
): Promise<deleteOneUpdateResponse> => {
	return customFetch<deleteOneUpdateResponse>(getDeleteOneUpdateUrl(id), {
		...options,
		method: 'DELETE'
	});
};

export const getDeleteOneUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteOneUpdate>>,
		TError,
		DeleteOneUpdateMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteOneUpdate>>,
	TError,
	DeleteOneUpdateMutationVariables,
	TContext
> => {
	const mutationKey = ['deleteOneUpdate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteOneUpdate>>,
		DeleteOneUpdateMutationVariables
	> = (props) => {
		const { id } = props ?? {};

		return deleteOneUpdate(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteOneUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteOneUpdate>>
>;

export type DeleteOneUpdateMutationError = unknown;
export type DeleteOneUpdateMutationVariables = { id: number };

/**
 * @summary Delete an update record by ID
 */
export const useDeleteOneUpdate = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteOneUpdate>>,
			TError,
			DeleteOneUpdateMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteOneUpdate>>,
	TError,
	DeleteOneUpdateMutationVariables,
	TContext
> => {
	return useMutation(getDeleteOneUpdateMutationOptions(options), queryClient);
};
export type editOneUpdateResponse200 = {
	data: UpdateDTO;
	status: 200;
};

export type editOneUpdateResponse404 = {
	data: UpdateDTO;
	status: 404;
};

export type editOneUpdateResponseSuccess = editOneUpdateResponse200 & {
	headers: Headers;
};
export type editOneUpdateResponseError = editOneUpdateResponse404 & {
	headers: Headers;
};

export type editOneUpdateResponse = editOneUpdateResponseSuccess | editOneUpdateResponseError;

export const getEditOneUpdateUrl = (id: number) => {
	return `/update/${id}`;
};

/**
 * Updates specific fields of an existing update record using a JSON patch body.
 * @summary Edit an existing update record (Patch)
 */
export const editOneUpdate = async (
	id: number,
	jsonNode: JsonNode,
	options?: Parameters<typeof customFetch>[1]
): Promise<editOneUpdateResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit['headers']>
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return customFetch<editOneUpdateResponse>(getEditOneUpdateUrl(id), {
		...options,
		method: 'PATCH',
		headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
		body: JSON.stringify(jsonNode)
	});
};

export const getEditOneUpdateMutationOptions = <TError = UpdateDTO, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof editOneUpdate>>,
		TError,
		EditOneUpdateMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof editOneUpdate>>,
	TError,
	EditOneUpdateMutationVariables,
	TContext
> => {
	const mutationKey = ['editOneUpdate'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof editOneUpdate>>,
		EditOneUpdateMutationVariables
	> = (props) => {
		const { id, data } = props ?? {};

		return editOneUpdate(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type EditOneUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof editOneUpdate>>>;
export type EditOneUpdateMutationBody = JsonNode;
export type EditOneUpdateMutationError = UpdateDTO;
export type EditOneUpdateMutationVariables = { id: number; data: JsonNode };

/**
 * @summary Edit an existing update record (Patch)
 */
export const useEditOneUpdate = <TError = UpdateDTO, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof editOneUpdate>>,
			TError,
			EditOneUpdateMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof editOneUpdate>>,
	TError,
	EditOneUpdateMutationVariables,
	TContext
> => {
	return useMutation(getEditOneUpdateMutationOptions(options), queryClient);
};
